name: CI Build ZMK Config

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-firmware:
    runs-on: ubuntu-latest
    env:
      ZMK_VERSION: ${{ secrets.ZMK_VERSION }}
      ZEPHYR_SDK_INSTALL_DIR: ${{ runner.tool_cache }}/zephyr-sdk
      ZEPHYR_TOOLCHAIN_VARIANT: zephyr
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: false

      - name: Cache dependencies & build
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.west
            build/
          key: ${{ runner.os }}-zmk-${{ hashFiles('manifest.yml','**/CMakeLists.txt') }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install West CLI
        run: pip install west

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake ninja-build \
            gperf ccache dfu-util device-tree-compiler wget python3-pip python3-setuptools

      - name: Install Zephyr SDK
        run: |
          ZEPHYR_SDK_VERSION=0.16.1
          wget https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v$ZEPHYR_SDK_VERSION/zephyr-sdk-$ZEPHYR_SDK_VERSION-linux-x86_64.tar.xz
          mkdir -p $ZEPHYR_SDK_INSTALL_DIR
          tar xf zephyr-sdk-$ZEPHYR_SDK_VERSION-linux-x86_64.tar.xz -C $ZEPHYR_SDK_INSTALL_DIR --strip-components=1

      - name: West init & update ZMK
        run: |
          west init -l . -m https://github.com/zmkfirmware/zmk --mr $ZMK_VERSION
          west update
          west zephyr-export

      - name: Build firmware
        run: |
          BOARD=nice_nano_kbd
          west build -d build/$BOARD -b $BOARD app

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: firmware
          path: build/**/zephyr/*.uf2

      - name: Create GitHub Release
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.sha }}
          files: build/**/zephyr/*.uf2
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

